version: '3.8'

services:
  jenkins-master:
    image: jenkins/jenkins:latest
    container_name: jenkins-master
    volumes:
      - D:/Programs/Jenkins:/var/jenkins_home
    ports:
      - 8080:8080
      - 50000:50000
    networks:
      - jenkins-networks

  jenkins-agent1:
    build: ./jenkins-agent1
    container_name: jenkins-agent1
    volumes:
      - D:/Programs/JenkinsAgents/agent1:/home/jenkins_agent1
    networks:
      - jenkins-networks

networks:
  jenkins-networks:
    driver: bridge